from .create_blog import CreateBlogView
from .edit_blog import EditBlogView
from .list_genre import ListGenreView
from .create_blog_not_thumbnail import CreateBlogNotThumbnailView
from .list_blog import ListBlogView
from .detail_blog import DetailBlogView
from .detail_blog_befor_purchase import DetailBlogBeforPurchaseView
from .buy_blog import BuyBlogView
from .get_bought_blog import GetBoughtView
from .blog_body import BlogBodyView
from .list_blog_author import ListBlogAuthorView
from .list_mine_blog import ListMineBlogView
from .edit_blog_note_thumbnail import EditBlogNotThumbnailView
